version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - COMMON_PASSWORD_PART=CHANGEME
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: